"""Shared key definitions for IVASTBOT HRI core logic."""

# Person position keys
NO_PERSON = "NO_PERSON"
PERSON_LEFT = "PERSON_LEFT"
PERSON_CENTER = "PERSON_CENTER"
PERSON_RIGHT = "PERSON_RIGHT"

# Facial expression keys
EXPR_NEUTRAL = "EXPR_NEUTRAL"
EXPR_HAPPY = "EXPR_HAPPY"
EXPR_SURPRISE = "EXPR_SURPRISE"
EXPR_CONFUSED = "EXPR_CONFUSED"
EXPR_UNKNOWN = "EXPR_UNKNOWN"

# High-level action keys
IDLE = "IDLE"
LOOK_LEFT = "LOOK_LEFT"
LOOK_RIGHT = "LOOK_RIGHT"
LOOK_CENTER = "LOOK_CENTER"
SHOW_NEUTRAL_FACE = "SHOW_NEUTRAL_FACE"
SHOW_HAPPY_FACE = "SHOW_HAPPY_FACE"
SHOW_THINKING_FACE = "SHOW_THINKING_FACE"
SHOW_GUIDING_FACE = "SHOW_GUIDING_FACE"
WAVE_HAND = "WAVE_HAND"
POINT_LEFT = "POINT_LEFT"
POINT_RIGHT = "POINT_RIGHT"
POINT_FORWARD = "POINT_FORWARD"
GUIDE_TO_TARGET = "GUIDE_TO_TARGET"
STOP_ACTION = "STOP_ACTION"

PERSON_KEYS = (
    NO_PERSON,
    PERSON_LEFT,
    PERSON_CENTER,
    PERSON_RIGHT,
)

EXPRESSION_KEYS = (
    EXPR_NEUTRAL,
    EXPR_HAPPY,
    EXPR_SURPRISE,
    EXPR_CONFUSED,
    EXPR_UNKNOWN,
)

ACTION_KEYS = (
    IDLE,
    LOOK_LEFT,
    LOOK_RIGHT,
    LOOK_CENTER,
    SHOW_NEUTRAL_FACE,
    SHOW_HAPPY_FACE,
    SHOW_THINKING_FACE,
    SHOW_GUIDING_FACE,
    WAVE_HAND,
    POINT_LEFT,
    POINT_RIGHT,
    POINT_FORWARD,
    GUIDE_TO_TARGET,
    STOP_ACTION,
)

ALL_KEYS = PERSON_KEYS + EXPRESSION_KEYS + ACTION_KEYS

__all__ = (
    "NO_PERSON",
    "PERSON_LEFT",
    "PERSON_CENTER",
    "PERSON_RIGHT",
    "EXPR_NEUTRAL",
    "EXPR_HAPPY",
    "EXPR_SURPRISE",
    "EXPR_CONFUSED",
    "EXPR_UNKNOWN",
    "IDLE",
    "LOOK_LEFT",
    "LOOK_RIGHT",
    "LOOK_CENTER",
    "SHOW_NEUTRAL_FACE",
    "SHOW_HAPPY_FACE",
    "SHOW_THINKING_FACE",
    "SHOW_GUIDING_FACE",
    "WAVE_HAND",
    "POINT_LEFT",
    "POINT_RIGHT",
    "POINT_FORWARD",
    "GUIDE_TO_TARGET",
    "STOP_ACTION",
    "PERSON_KEYS",
    "EXPRESSION_KEYS",
    "ACTION_KEYS",
    "ALL_KEYS",
)
