from config import (  # noqa: F401
    BASE_DIR,
    COLLECTION,
    DATASET_PATH,
    DB_PATH,
    DISTANCE_THRESHOLD,
    EMBED_MODEL,
    LLM_MODEL_FALLBACK,
    LLM_MODEL_PRIMARY,
    LOG_PATH,
    TOP_K,
)

